spasalon/services/urls.py
from django.urls import path

from services.views import (
    ServiceView,
    ServicesView,
)

app_name = "services"
urlpatterns = [
    path("", ServicesView.as_view(), name="services"),
    path("<int:pk>/", ServiceView.as_view(), name="service"),
]

spasalon/spasalon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path('feedback/', include("feedback.urls")),
    path("reception/", include("reception.urls")),
    path("reviews/", include("reviews.urls")),
    path("services/", include("services.urls")),
    path("specialists/", include("specialists.urls")),
    path("users/", include("users.urls")),
    path("users/", include(urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

spasalon/users/urls.py
import django.contrib.auth.views
from django.urls import path, re_path, reverse_lazy

from users.views import SignUpView, PasswordReset, ProfileView

app_name = "users"

urlpatterns = [
    path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordReset.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    re_path(
        r"password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

spasalon/services/models.py
from django.db import models
from django.utils.safestring import mark_safe

from sorl.thumbnail import get_thumbnail

class Services(models.Model):
    name = models.CharField(
        'название услуги',
        max_length=50
    )
    is_published = models.BooleanField(
        'публикация',
        default=True
    )
    description = models.TextField(
        'описание услуги'
    )
    price = models.IntegerField(
        'стоимость услуги'
    )
    main_image = models.ImageField(
        'путь до изображения товара',
        upload_to='items/',
        null=True,
        blank=True
    )

    @property
    def get_image(self):
        return get_thumbnail(self.main_image, '250x150', quality=51)

    def image_tmb(self):
        if self.main_image:
            return mark_safe(f'<img src={self.get_image.url} />')
        return 'нет изображения'

    image_tmb.short_description = 'изображение товара'
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = 'услуга'
        verbose_name_plural = 'услуги'

    def __str__(self):
        return self.name
    

class ServiceImages(models.Model):
    service_photos = models.ForeignKey(
        Services,
        related_name='images',
        on_delete=models.CASCADE,
        verbose_name='фотографии товара',
    )
    image = models.ImageField(
        'путь до фотографии товара',
        upload_to='items/',
    )

    @property
    def get_image(self):
        return get_thumbnail(self.image, '600x300', crop='center', quality=51)

    def image_tmb(self):
        if self.gallery_image:
            return mark_safe(f'<img src={self.get_image.url} /')
        return 'нет изображения'

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = 'фотография изображения'
        verbose_name_plural = 'фотографии изображения'

spasalon/services/views.py
from django.views.generic import DetailView, ListView
from django.db import models

from services.models import Services, ServiceImages

class ServicesView(ListView):
    template_name = "services/services.html"
    context_object_name = "services"

    def get_queryset(self):
        return Services.objects.filter(is_published=True)
    

class ServiceView(DetailView):
    template_name = "services/service.html"
    context_object_name = "service"
    model = Services
    queryset = model.objects.all()

    def get_object(self):
        service_images = ServiceImages.objects.only(
            'service_photos', 'image'
        )
        service_images_field = ServiceImages.service_photos
        return self.queryset.prefetch_related(
                models.Prefetch(
                service_images_field.field.related_query_name(),
                queryset=service_images,
            )).filter(is_published=True).get(pk=self.kwargs["pk"])

spasalon/templates/services/service.html
{% extends 'base.html' %}

{% block title %}
  Услуга
{% endblock %}

{% load static %}

{% block content %}
  <h1>{{ service.name }}</h1>
  <h5>Стоимость: {{ service.price }}</h5>
  {% load thumbnail %}
  <div class="d-block">
  {% thumbnail service.main_image '550x350' as ph %}
      <img class='img-fluid' src="{{ ph.url }}"
                 width="{{ ph.width }}"
                 height="{{ ph.height }}"
                 alt="картина">
  {% endthumbnail %}
  </div>
  {% if service.images %}
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        {% for service_image in service.images.all %}
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-label="Slide forloop.counter" aria-current="true"></button>
        {% endfor %}
      </div>
      <div class="carousel-inner">
        {% for service_image in service.images.all %}
          <div class="carousel-item{% if forloop.first %} active{% endif %} text-center">
            <img src="{{ service_image.get_image.url }}" />
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  {% endif %}
  <h4 class="mt-2">Об услуге</h4>
  <p class="col-6 mx-auto">{{ service.description }}</p>
  <div>
    <a href="{% url 'services:services' %}" class="btn btn-primary bi me-2 mb-2" role="button">
        К каталогу услуг
    </a>
  </div>
{% endblock %}

spasalon/templates/services/services.html
{% extends 'base.html' %}

{% block title %}
Услуги
{% endblock title %}

{% load thumbnail %}

{% block content %}
    <h1>Наши услуги</h1>
    {% for service in services %}
        <div class="card bg-dark text-white">
            <div class="d-block">
                {% thumbnail service.main_image '700x350' crop='center' as ph %}
                    <img class='img-fluid' src="{{ ph.url }}"
                            width="{{ ph.width }}"
                            height="{{ ph.height }}"
                            alt="картина">
                {% endthumbnail %}
            </div>
            <div class="card-img-overlay text-black">
            <h2 class="card-title"><a class='btn btn-dark' href={% url 'services:service' service.pk %}>{{ service.name }}</a></h2>
            <p class="card-text">Стоимость: {{ service.price }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock content %}