spasalon/spasalon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path('feedback/', include("feedback.urls")),
    path("reception/", include("reception.urls")),
    path("reviews/", include("reviews.urls")),
    path("services/", include("services.urls")),
    path("specialists/", include("specialists.urls")),
    path("users/", include("users.urls")),
    path("users/", include(urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

spasalon/specialists/urls.py
from django.urls import path

from specialists.views import (
    SpecialistView,
    SpecialistsView,
)

app_name = "specialists"
urlpatterns = [
    path("", SpecialistsView.as_view(), name="specialists"),
    path("<int:pk>/", SpecialistView.as_view(), name="specialist"),
]

spasalon/users/urls.py
import django.contrib.auth.views
from django.urls import path, re_path, reverse_lazy

from users.views import SignUpView, PasswordReset, ProfileView

app_name = "users"

urlpatterns = [
    path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordReset.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    re_path(
        r"password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

spasalon/specialists/models.py
from django.db import models
from django.utils.safestring import mark_safe
from sorl.thumbnail import get_thumbnail

class Specialists(models.Model):
    name = models.CharField(
        'имя',
        max_length=50
    )
    surname = models.CharField(
        'фамилия',
        max_length=50
    )
    description = models.TextField(
        'о специалисте'
    )
    person_image = models.ImageField(
        'путь до изображения специалиста',
        upload_to='items/',
    )
    is_published = models.BooleanField(
        'опубликовано',
        default=True
    )

    @property
    def get_image(self):
        return get_thumbnail(self.person_image, '250x250', quality=51)

    def image_tmb(self):
        if self.person_image:
            return mark_safe(f'<img src={self.get_image.url} />')
        return 'нет изображения'

    image_tmb.short_description = 'изображение товара'
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = 'специалист'
        verbose_name_plural = 'специалисты'

    def __str__(self):
        return self.name

spasalon/specialists/views.py
from django.views.generic import DetailView, ListView

from specialists.models import Specialists

class SpecialistsView(ListView):
    template_name = "specialists/specialists.html"
    context_object_name = "specialists"

    def get_queryset(self):
        return Specialists.objects.filter(is_published=True)
    

class SpecialistView(DetailView):
    template_name = "specialists/specialist.html"
    context_object_name = "specialist"
    model = Specialists
    queryset = model.objects.all()

    def get_object(self):
        return self.queryset.filter(is_published=True).get(pk=self.kwargs["pk"])

spasalon/templates/specialists/specialist.html
{% extends 'base.html' %}

{% block title %}
  Специалистам
{% endblock %}

{% load static %}

{% block content %}
  <h1>{{ specialist.surname }} {{ specialist.name }}</h1>
  {% load thumbnail %}
  <div class="d-block">
  {% thumbnail specialist.person_image '550x350' as ph %}
      <img class='img-fluid' src="{{ ph.url }}"
                 width="{{ ph.width }}"
                 height="{{ ph.height }}"
                 alt="картина">
  {% endthumbnail %}
  </div>
  <h4 class="mt-2">О специалисте</h4>
  <p class="col-6 mx-auto">{{ specialist.description }}</p>
  <div>
    <a href="{% url 'specialists:specialists' %}" class="btn btn-primary bi me-2 mb-2" role="button">
        К специалистам
    </a>
  </div>
{% endblock %}

spasalon/templates/specialists/specialists.html
{% extends 'base.html' %}

{% block title %}
  Спецаилисты
{% endblock %}

{% load thumbnail %}

{% block content %}
  <h1>Специалисты</h1>
  {% for specialist in specialists %}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% if forloop.counter0 >= 3 and forloop.counter0|divisibleby:3 %}
      </div>
    {% endif %}
    {% endif %}
    <div class='col-4'>
        <div class="card">
            {% thumbnail specialist.person_image '700x350' crop='center' as ph %}
                <img class='img-fluid' src="{{ ph.url }}"
                        width="{{ ph.width }}"
                        height="{{ ph.height }}"
                        alt="картина">
            {% endthumbnail %}
            <div class="card-body">
            <h5 class="card-title">{{ specialist.surname }} {{ specialist.name }}</h5>
            </div>
            <div class="card-body">
            <a href="{% url 'specialists:specialist' specialist.pk %}" class="card-link">Перейти к странице специалиста</a>
            </div>
        </div>
    </div>
    {% if forloop.last %}
      </div>
    {% endif %}
  {% endfor %}
{% endblock %}