spasalon/feedback/urls.py
from django.urls import path

from feedback.views import FeedbackView

app_name = 'feedback'
urlpatterns = [
    path('', FeedbackView.as_view(), name='feedback')
]

spasalon/homepage/urls.py
from django.urls import path

from homepage.views import (
    HomepageView,
)

app_name = "homepage"
urlpatterns = [
    path("", HomepageView.as_view(), name="home"),
]

spasalon/reviews/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from reviews.views import (
    AddReviewView,
    ReviewsView,
)

app_name = "reviews"
urlpatterns = [
    path("", ReviewsView.as_view(), name="reviews"),
    path("add_review/", login_required(AddReviewView.as_view()), name="add_review"),
]

spasalon/services/urls.py
from django.urls import path

from services.views import (
    ServiceView,
    ServicesView,
)

app_name = "services"
urlpatterns = [
    path("", ServicesView.as_view(), name="services"),
    path("<int:pk>/", ServiceView.as_view(), name="service"),
]

spasalon/spasalon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path('feedback/', include("feedback.urls")),
    path("reception/", include("reception.urls")),
    path("reviews/", include("reviews.urls")),
    path("services/", include("services.urls")),
    path("specialists/", include("specialists.urls")),
    path("users/", include("users.urls")),
    path("users/", include(urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

spasalon/users/urls.py
import django.contrib.auth.views
from django.urls import path, re_path, reverse_lazy

from users.views import SignUpView, PasswordReset, ProfileView

app_name = "users"

urlpatterns = [
    path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordReset.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    re_path(
        r"password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

spasalon/templates/includes/base_form.html
<form method='post' enctype='multipart/form-data'>
    {% for field in form %}
        {% csrf_token %}
        <div class='col-sm-5 mx-auto'>
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <small class='fw-light'>{{ field.help_text }}</small>
            {% endif %}
            {% if field.errors %}
                <div class='alert alert-danger'>
                    {{ field.errors }}
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <button class='btn btn-secondary mt-2 mb-3' type='submit'>Отправить</button>
</form>

spasalon/templates/includes/footer.html
<footer>
    <div class="container">
    <p class="text-center text-dark">&copy; Made in {% now "Y" %} by Daniil Petrov</p>
    </div>
</footer>
  

spasalon/templates/includes/header.html
{% load static %}

<header class="p-2 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <img src={% static 'img/main.png' %} width="150" height="64" alt="Иконка сайта" class="bi me-2">

      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href={% url 'homepage:home' %} class="nav-link px-2
              {% if view_name == 'homepage:home' %}
                text-secondary
              {% else %}
                text-white
              {% endif %}">Главная</a>
          </li>
          <li><a href={% url 'reviews:reviews' %} class="nav-link px-2
              {% if view_name == 'reviews:reviews' %}
                text-secondary
              {% else %}
                text-white
              {% endif %}">Отзывы</a>
          </li>
          <li><a href={% url 'services:services' %} class="nav-link px-2
              {% if view_name == 'services:services' %}
                text-secondary
              {% else %}
                text-white
              {% endif %}">Услуги</a>
          </li>
          <li><a href={% url 'specialists:specialists' %} class="nav-link px-2
                {% if view_name == 'specialists:specialists' %}
                    text-secondary
                {% else %}
                    text-white
                {% endif %}">Специалисты</a>
            </li>
          <li><a href={% url 'feedback:feedback' %} class="nav-link px-2
              {% if view_name == 'feedback:feedback' %}
                text-secondary
              {% else %}
                text-white
              {% endif %}">Обратная связь</a>
          </li>
        </ul>
      {% endwith %}

      <div class="text-end">
        {% if request.user.is_authenticated %}
          <a href="{% url 'users:profile' %}" role="button" class="btn btn-primary bi me-2">Профиль</a>
          <a href="{% url 'reception:reception' %}" role="button" class="btn btn-primary">Записаться на приём</a>
        {% else %}
          <a href="{% url 'users:login' %}" role="button" class="btn btn-primary bi me-2">Войти</a>
          <a href="{% url 'users:sign_up' %}" role="button" class="btn btn-primary">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>